#!/bin/bash

script_path="$(dirname "$(readlink -f "$0")")"
build_output_path="$1"
platform_nm_util="$2"

ot_lib_artifacts=(
	"libtcplp-ftd.a"
	"libopenthread-ftd.a"
	"libopenthread-cli-ftd.a"
	"libtcplp-mtd.a"
	"libopenthread-mtd.a"
	"libopenthread-cli-mtd.a"
	"libopenthread-platform.a"
	"libopenthread-platform-utils.a"
	"libopenthread-rcp.a"
	"libopenthread-radio.a"
	"libopenthread-radio-cli.a"
	"libopenthread-ncp-ftd.a"
	"libopenthread-ncp-mtd.a"
	"libopenthread-radio-spinel.a"
	"libopenthread-spinel-ncp.a"
	"libopenthread-url.a"
	"libopenthread-hdlc.a"
)

ot_lib_gnerated=()
for ot_lib in "${ot_lib_artifacts[@]}"; do
	result="$(find "$build_output_path" -name "$ot_lib")"
	if [ -n "$result" ]; then
		ot_lib_gnerated+=("$result")
	fi
done
if (( ${#ot_lib_gnerated[@]} == 0 )); then
    echo no any openthread libraries are generated
    exit -1
fi

"$script_path/libmerge" "$build_output_path/zephyr/libopenthread.a" "${ot_lib_gnerated[@]}"
"$platform_nm_util" --strip-unneeded "$build_output_path/zephyr/libopenthread.a"
echo "Generated openthread library:"
sha256sum "$build_output_path/zephyr/libopenthread.a"
