/*
 * Copyright (c) 2026 Telink Semiconductor
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_TLX_KSCAN_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_TLX_KSCAN_H_

#define TLX_KSCAN_COL_EXT_PULL_UP   0x10
#define TLX_KSCAN_COL_EXT_PULL_DOWN 0x20
#define TLX_KSCAN_COL_INT_PULL_UP   0x13
#define TLX_KSCAN_COL_INT_PULL_DOWN 0x22

#define TLX_KSCAN_DEBOUNCE_PERIOD_8MS  0x2
#define TLX_KSCAN_DEBOUNCE_PERIOD_12MS 0x3
#define TLX_KSCAN_DEBOUNCE_PERIOD_16MS 0x4
#define TLX_KSCAN_DEBOUNCE_PERIOD_20MS 0x5
#define TLX_KSCAN_DEBOUNCE_PERIOD_24MS 0x6
#define TLX_KSCAN_DEBOUNCE_PERIOD_28MS 0x7

#define TLX_KSCAN_SCAN_TIMES_DOUBLE 0
#define TLX_KSCAN_SCAN_TIMES_TRIPLE 1

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_TLX_KSCAN_H_ */
