/*
 * Copyright (c) 2026 Telink Semiconductor
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_TLX_KSCAN_ANA_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_TLX_KSCAN_ANA_H_

#define TLX_KSCAN_ANA_PIN_GROUP_ID_0 0
#define TLX_KSCAN_ANA_PIN_GROUP_ID_1 1
#define TLX_KSCAN_ANA_PIN_GROUP_ID_2 2
#define TLX_KSCAN_ANA_PIN_GROUP_ID_3 3

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_TLX_KSCAN_ANA_H_ */
