CONFIG_CPP=y
CONFIG_LOG=y
# See: https://github.com/zephyrproject-rtos/zephyr/issues/34269
# CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_NETWORKING=y
CONFIG_NET_L2_OPENTHREAD=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=32768
CONFIG_MAIN_STACK_SIZE=8192
