CONFIG_TELINK_OPUS_REMOTE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_PBUF_RX_READ_BUF_SIZE=9000

# INFO log level by default, uncomment if DEBUG needed:
# CONFIG_TELINK_OPUS_REMOTE_LOG_LEVEL_DEBG=y
