# Copyright (c) 2026 Telink Semiconductor
# SPDX-License-Identifier: Apache-2.0

# required openthread version
CONFIG_OPENTHREAD_THREAD_VERSION_1_4=y
# make ot cli library
CONFIG_OPENTHREAD_SHELL=y
# Telink platform required
CONFIG_OPENTHREAD_CSL_RECEIVE_TIME_AHEAD=2000
