# Copyright (c) 2026 Telink Semiconductor
# SPDX-License-Identifier: Apache-2.0

CONFIG_NETWORKING=y
CONFIG_SHELL=y

# make ot cli library
# do not move to openthread config
# it's enabled during libary build
# but in project it's user -
# thrown away due to entry point
CONFIG_OPENTHREAD_SHELL=y
