# Copyright (c) 2026 Telink Semiconductor
# SPDX-License-Identifier: Apache-2.0

CONFIG_OPENTHREAD_MTD=y
CONFIG_OPENTHREAD_SRP_CLIENT=y
CONFIG_OPENTHREAD_DNS_CLIENT=y
CONFIG_OPENTHREAD_SLAAC=y

CONFIG_OPENTHREAD_NUM_MESSAGE_BUFFERS=64
